## This workflow uses actions that are not certified by GitHub.
## They are provided by a third-party and are governed by
## separate terms of service, privacy policy, and support
## documentation.
#
#name: Dart
#
#on:
#  push:
#    branches: [ "cicd_branch" ]
#  pull_request:
#    branches: [ "cicd_branch" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      # Note: This workflow uses the latest stable version of the Dart SDK.
#      # You can specify other versions if desired, see documentation here:
#      # https://github.com/dart-lang/setup-dart/blob/main/README.md
#      # - uses: dart-lang/setup-dart@v1
#      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
#
#      - name: Install dependencies
#        run: dart pub get
#
#      # Uncomment this step to verify the use of 'dart format' on each commit.
#      # - name: Verify formatting
#      #   run: dart format --output=none --set-exit-if-changed .
#
#      # Consider passing '--fatal-infos' for slightly stricter analysis.
#      - name: Analyze project source
#        run: dart analyze
#
#      # Your project will need to have tests in test/ and a dependency on
#      # package:test for this step to succeed. Note that Flutter projects will
#      # want to change this to 'flutter test'.
#      - name: Run tests
#        run: dart test
# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
  # Runs this action when you push on master
  push:
    branches: [ "cicd_branch" ]
  # Runs this when a PR against master is created
  pull_request:
    branches: [ "cicd_branch" ]

env:
  CI: false

jobs:
  Build:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: windows-latest

    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      #      - run: flutter test

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
#
#      # Clones the project on the machine
#      - uses: actions/checkout@v4
#
#      # Installs flutter and related dependency on this machine
#      - name: Setup Flutter
#        uses: actions/flutter-action@v2
#        with:
#          channel: 'stable'
#          flutter-version: '3.22.1'
#          # ^ If you want to use a specific version of flutter
#
#      # Fetches proj dependencies from pub
#      - name: Install dependencies
#        run: flutter pub get
#        # ^ If you want to use a specific version of flutter
#      - run: flutter build apk
#      - name: Push to Releases
#        uses: actions/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
##          ,build/ios/iphoneos/app.ipa
