# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
  # Runs this action when you push on master
  push:
    branches: [ "cicd_branch" ]
  # Runs this when a PR against master is created
  pull_request:
    branches: [ "cicd_branch" ]

jobs:
  flutter_job:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: windows

    steps:

      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Installs flutter and related dependency on this machine
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
          # flutter-version: '3.16.8'
          # ^ If you want to use a specific version of flutter

      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get
        # ^ If you want to use a specific version of flutter
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
#          ,build/ios/iphoneos/app.ipa